import React from 'react'
function Dataprovider() {
  return (
    <>
    
    <div className="listing">
            <div className="container">
                <header>
                    <img src="" alt=""></img>
                    <h1>Mobula</h1>
                    <span>
                    Mobula is the decentralized data aggregator, allowing dApps to integrate trustable and on-chain data APIs. The Mobula dApp allows any user to participate in the data aggregation process simply by joining the Protocol DAO.
                    </span>
                    <br></br>
                    <span>
                    MOBL is the native utility token that is used for the governance of the project (from treasury management to Protocol-related decisions), to reward the Protocol DAO members for their work and to redistribute the profit generated by the platform to holders via staking pools.
                    </span>
                </header>
                <div className="line"></div>
                </div>
                </div>
                </>
  )
}

export default Dataprovider